type FollowUpsType = {
  date: string;
  status: string;
};

type PatientType = {
  patient: {
    _id: string;
    name: string;
    followUps: FollowUpsType[];
  };
};

//[css generated by chatgpt]
const FollowupCard = ({ patient }: PatientType) => {
  return (
    <div
      key={patient._id}
      style={{
        border: "1px solid #ddd",
        borderRadius: "8px",
        padding: "15px",
        marginBottom: "15px",
        boxShadow: "2px 2px 10px rgba(0, 0, 0, 0.1)",
        maxWidth: "400px",
        backgroundColor: "#fff",
      }}
    >
      <h3
        style={{
          marginBottom: "10px",
          color: "#2c3e50",
          borderBottom: "2px solid #3498db",
          paddingBottom: "5px",
        }}
      >
        {patient.name} 
        <span style={{
          marginBottom: "10px",
          marginLeft:'5px',
          color: "#2c3e50",
          fontSize:'10px'
        }}>({patient._id})</span>
      </h3>     
      <ul style={{ padding: 0, listStyle: "none", margin: 0 }}>
        {patient.followUps.map((followUp, key) => (
          <li
            key={key}
            style={{
              padding: "8px",
              borderRadius: "5px",
              backgroundColor:
                followUp.status === "Completed" ? "#2ecc71" : "#f39c12",
              color: "white",
              marginBottom: "5px",
              fontWeight: "bold",
              textAlign: "center",
            }}
          >
            {followUp?.date ?? "N/A"} - {followUp.status}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default FollowupCard;
